services:
  birdnet-pi:
    image: ghcr.io/mithro/birdnet-pi:latest
    container_name: birdnet-pi
    privileged: true
    cgroupns: host
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8081:8081"
    volumes:
      - ./birdnet-pi-data:/home/birdnet/BirdNET-Pi/birdsongs
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/snd:/dev/snd
    tmpfs:
      - /run
      - /run/lock
    environment:
      - TZ=Australia/Adelaide
