services:
  birdnet-pi:
    image: ghcr.io/mithro/birdnet-pi:latest
    container_name: birdnet-pi
    privileged: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8081:8081"
    volumes:
      - ./data/StreamData:/home/birdnet/BirdSongs/StreamData
      - ./data/By_Date:/home/birdnet/BirdSongs/Extracted/By_Date
      - ./birdnet.conf:/home/birdnet/BirdNET-Pi/birdnet.conf
      - ./asoundrc:/home/birdnet/.asoundrc:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    devices:
      - /dev/snd:/dev/snd
    tmpfs:
      - /run
      - /run/lock
    environment:
      - TZ=Australia/Adelaide
